### ISSUE TITLE
problem with fork

### ISSUE THREAD

**Issue by re1ocate** [Lezhek/SCSST#1]
Sorry for writing in another repo, but because your repo for snieg is a fork, the "issue" tab is not available there.

When downloading a save, I get an error.

![image](https://github.com/user-attachments/assets/47bf0ba0-64c4-4e90-af4e-17323f1cde24)

**Comment by Lezhek** [comment]
> Sorry for writing in another repo, but because your repo for snieg is a fork, the "issue" tab is not available there.
> 
> When downloading a save, I get an error.
> 
> ![image](https://private-user-images.githubusercontent.com/147985072/379497685-47bf0ba0-64c4-4e90-af4e-17323f1cde24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTc5MTQsIm5iZiI6MTcyOTc1NzYxNCwicGF0aCI6Ii8xNDc5ODUwNzIvMzc5NDk3Njg1LTQ3YmYwYmEwLTY0YzQtNGU5MC1hZjRlLTE3MzIzZjFjZGUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwODEzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTY0OTIxNmI4N2NmYTc0M2QwYjliZWJjZjk5YmQxNTMwNzczMWFiOWFjZDk4MjIzNDM4OGJkMTFlYTY5YTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FptSS-QMYb-xkz5noPuh8wY378xQrniVRCq5VJ9eon4)

Try submit an issue in original snieg repo but I don't think it will be solved because I sent the code to the developer and he is not interested in that "dormant project" anymore . 
Did you install all required packages? 
I honestly have no idea how the whole discord bot part of the code works. 
My fork only touches the part where it's determined how local folders are handled so I can not help you since it's discord bot issue and I can only guess that discord may have broke something because they changed a lot of things about bots since this script have been made, try to play around with bot settings in discord web panel. 

As an alternative I'd suggest to use the thing that you submitted an issue to I had a blast using it with my friends and it's way better in terms of usability.
